services:
  - type: web
    name: estimate-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://estimate_app_user:KrishiKranti%402026@krishikranti.tyerpvc.mongodb.net/estimate_app_db?retryWrites=true&w=majority
