services:
  - type: web
    name: estimate-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://ebs4socioxpark_db_user:Y7qCxC5Wx3DcTrzt@cluster0.bgo9eqf.mongodb.net/estimate_app_db?retryWrites=true&w=majority&appName=Cluster0
